//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huida81_WPF.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huida81_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string MotherboardListDescription {
            get {
                return ResourceManager.GetString("MotherboardListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Motherboard.
        /// </summary>
        public static string MotherboardPageTitle {
            get {
                return ResourceManager.GetString("MotherboardPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Motherboard.
        /// </summary>
        public static string ShellMotherboardPage {
            get {
                return ResourceManager.GetString("ShellMotherboardPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string BIOSListDescription {
            get {
                return ResourceManager.GetString("BIOSListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to BIOS.
        /// </summary>
        public static string BIOSPageTitle {
            get {
                return ResourceManager.GetString("BIOSPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to BIOS.
        /// </summary>
        public static string ShellBIOSPage {
            get {
                return ResourceManager.GetString("ShellBIOSPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string CPUListDescription {
            get {
                return ResourceManager.GetString("CPUListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPUPageTitle {
            get {
                return ResourceManager.GetString("CPUPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string ShellCPUPage {
            get {
                return ResourceManager.GetString("ShellCPUPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string HDDListDescription {
            get {
                return ResourceManager.GetString("HDDListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        public static string HDDPageTitle {
            get {
                return ResourceManager.GetString("HDDPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        public static string ShellHDDPage {
            get {
                return ResourceManager.GetString("ShellHDDPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string PartitionListDescription {
            get {
                return ResourceManager.GetString("PartitionListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Partition.
        /// </summary>
        public static string PartitionPageTitle {
            get {
                return ResourceManager.GetString("PartitionPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Partition.
        /// </summary>
        public static string ShellPartitionPage {
            get {
                return ResourceManager.GetString("ShellPartitionPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string GraphicListDescription {
            get {
                return ResourceManager.GetString("GraphicListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string GraphicPageTitle {
            get {
                return ResourceManager.GetString("GraphicPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string ShellGraphicPage {
            get {
                return ResourceManager.GetString("ShellGraphicPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string DisplayListDescription {
            get {
                return ResourceManager.GetString("DisplayListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayPageTitle {
            get {
                return ResourceManager.GetString("DisplayPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string ShellDisplayPage {
            get {
                return ResourceManager.GetString("ShellDisplayPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string KeyboardListDescription {
            get {
                return ResourceManager.GetString("KeyboardListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string KeyboardPageTitle {
            get {
                return ResourceManager.GetString("KeyboardPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string ShellKeyboardPage {
            get {
                return ResourceManager.GetString("ShellKeyboardPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string MouseListDescription {
            get {
                return ResourceManager.GetString("MouseListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string MousePageTitle {
            get {
                return ResourceManager.GetString("MousePageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string ShellMousePage {
            get {
                return ResourceManager.GetString("ShellMousePage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string NetworkListDescription {
            get {
                return ResourceManager.GetString("NetworkListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkPageTitle {
            get {
                return ResourceManager.GetString("NetworkPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string ShellNetworkPage {
            get {
                return ResourceManager.GetString("ShellNetworkPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ActivityPageTitle {
            get {
                return ResourceManager.GetString("ActivityPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ShellActivityPage {
            get {
                return ResourceManager.GetString("ShellActivityPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Dark.
            /// </summary>
            public static string SettingsPageRadioButtonDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Light.
            /// </summary>
            public static string SettingsPageRadioButtonLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Default.
            /// </summary>
            public static string SettingsPageRadioButtonWindowsDefaultTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    }
}
